name: Trigger auto deployment for wfdesigner2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/wfdesigner2-AutoDeployTrigger-a3111428-7f81-4016-81b9-4bc668550455.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WFDESIGNER2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WFDESIGNER2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WFDESIGNER2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.WFDESIGNER2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WFDESIGNER2_REGISTRY_PASSWORD }}
          containerAppName: wfdesigner2
          resourceGroup: dev-poc-deploy-aci-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


