name: Trigger auto deployment for wfdesignergit

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/wfdesignergit-AutoDeployTrigger-3913769e-305b-4fa7-9b59-8cb5dd513847.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WFDESIGNERGIT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WFDESIGNERGIT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WFDESIGNERGIT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.WFDESIGNERGIT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WFDESIGNERGIT_REGISTRY_PASSWORD }}
          containerAppName: wfdesignergit
          resourceGroup: dev-poc-deploy-aci-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


